### ISSUE TITLE
darkplaces-rcon-util-0.1 doesn't compile with GHC 7.10.x

### ISSUE THREAD

**Issue by peti** [bacher09/darkplaces-rcon#1]
http://packdeps.haskellers.com/feed?needle=darkplaces-rcon-util

Would it be possible to get an updated release that can be built with GHC 7.10.x? We're running into these errors on NixOS: http://hydra.cryp.to/build/887223/log/raw.

**Comment by peti** [comment]
Will you release a new version?

**Comment by bacher09** [comment]
Yep, wait a minute.

**Comment by bacher09** [comment]
It seems hackage have problems with `if impl(time < 1.5)` directive in cabal file. 
It returns `Unknown compiler name 'time'`.

**Comment by bacher09** [comment]
Unfortunately it works only for compiller [version](https://github.com/bos/aeson/commit/730a8c42b75f38e241da39933b03735a7c905538).

**Comment by peti** [comment]
Yes, to achieve what you'd like to do, you need to define a flag, like `old-time`.

**Comment by peti** [comment]
Or use http://hackage.haskell.org/package/time-compat.

**Comment by bacher09** [comment]
Thanks for collaboration. Fixed in [0.1.1](https://github.com/bacher09/darkplaces-rcon/commits/0.1.1)
